# Generated by Django 3.0.3 on 2020-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0002_utilisateur_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
